name: Node.js TESTNET CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  BLOKARIA_WEBSITE: 'https://blokaria.com/'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Print ENV KEYS
      ## Reference your environment variables
      run: |
        echo "The API key is: $BLOKARIA_WEBSITE" 
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_TEST_SECRET: ${{ secrets.TEST_SECRET }}
        envkey_BLOKARIA_WEBSITE: ${{ env.BLOKARIA_WEBSITE }} 
        file_name: .env
    - name: Copy file .env via ssh password
      uses: appleboy/scp-action@master
      with:
        host: '144.91.89.39'
        username: 'siki'
        key: ${{ secrets.SSH_KEY_DEV }}
        port: 22
        source: '.env'
        target: '/var/www/avalanche_transactions'
    - uses: actions/checkout@master
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: '144.91.89.39'
        username: 'siki'
        key: ${{ secrets.SSH_KEY_DEV }}
        port: 22
        source: "."
        target: "/var/www/avalanche_transactions"
        
    - name: Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: '144.91.89.39'
        username: 'siki'
        key: ${{ secrets.SSH_KEY_DEV }}
        port: 22
        script: |
          cd /var/www/avalanche_transactions
          npm install
          pm2 restart avax
        
       
   
