name: Node.js AVAX DEV CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  BLOKARIA_WEBSITE: 'https://blokaria.com/'
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Print ENV KEYS
      ## Reference your environment variables
      run: |
        echo "The API keys is: $BLOKARIA_WEBSITE" 
        echo "The API keys is TEST_SECRET : ${{ secrets.TEST_SECRET }}" 
        echo "The API keys is SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}" 
        echo "Receiver Addr: BLA" 
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_TEST_SECRET: ${{ secrets.TEST_SECRET }}
        file_name: .env
    - name: Copy file .env via ssh password
      uses: appleboy/scp-action@master
      with:
        host: '185.193.66.140'
        username: 'admin'
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: '.env'
        target: "/opt/cardano/avalanche_transactions"
    - uses: actions/checkout@master
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: '185.193.66.140'
        username: 'admin'
        key: ${{ secrets.SSH_KEY_DEV }}
        port: 22
        source: "."
        target: "/opt/cardano/avalanche_transactions"
        
    - name: Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: '185.193.66.140'
        username: 'admin'
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /opt/cardano/avalanche_transactions
          npm install
          pm2 restart app
        
       
   
